# -*- coding: utf-8 -*-
"""Start.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JmKs0qeJqKH-PQ3ycGpU-X3Wxw1OJBIf

Напишите программу, которая выводит на печать "Сегодня я научусь делать домашние задание с помощью GitHub classroom!"
"""

